apiVersion: v1
kind: Pod
metadata:
  name: application-probe
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 5000
    readinessProbe:
      httpGet:
        path: /started
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 15
      periodSeconds: 20

