apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  selector:   # Match labels
    matchLabels:
      tier: frontend
  template:   # Pod template
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx