apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:                # specifications/contents for replicationcontroller
  replicas: 3
  selector:          # label selector for replicationcontroller
    app: nginx
  template:          # pod template
    metadata:
      name: nginx    # name of pod
      labels:        # pod label
        app: nginx
    spec:            # spec for containers
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

#akm- api version, kind, metadata, sepcifications

# Kuberenetes became multi tenant (multiple teams)